AllCops:
  # Include:
  #   - 'app'
  #   - 'spec'

  Exclude:
    - 'db/*'
    - 'config/*'
    - 'script/*'
    - 'bin/*'


Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
